/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as PlacePlaceIdRouteImport } from './routes/place/$placeId'
import { Route as RecommendIndexRouteImport } from './routes/recommend/index'
import { Route as ShellCourseIndexRouteImport } from './routes/_shell/course/index'
import { Route as ShellCourseCreateRouteImport } from './routes/_shell/course/create'
import { Route as ShellCourseDiscoverRouteImport } from './routes/_shell/course/discover'
import { Route as ShellMapIndexRouteImport } from './routes/_shell/map/index'
import { Route as ShellMyIndexRouteImport } from './routes/_shell/my/index'
import { Route as ShellMyDataSourcesRouteImport } from './routes/_shell/my/data-sources'
import { Route as ShellMyPermissionsRouteImport } from './routes/_shell/my/permissions'
import { Route as ShellMyPreferencesRouteImport } from './routes/_shell/my/preferences'
import { Route as ShellMyRankingRouteImport } from './routes/_shell/my/ranking'
import { Route as ShellMyReviewsRouteImport } from './routes/_shell/my/reviews'
import { Route as ShellMySavedCoursesRouteImport } from './routes/_shell/my/saved-courses'
import { Route as ShellMySavedPlacesRouteImport } from './routes/_shell/my/saved-places'
import { Route as ShellMyTitlesRouteImport } from './routes/_shell/my/titles'
import { Route as ShellTravelersTravelerIdRouteImport } from './routes/_shell/travelers/$travelerId'
import { Route as LoginKakaoCallbackRouteImport } from './routes/login/kakao/callback'
import { Route as PlacePlaceIdReviewRouteImport } from './routes/place/$placeId_.review'
import { Route as ShellCourseCourseIdIndexRouteImport } from './routes/_shell/course/$courseId/index'
import { Route as ShellCourseCourseIdEditRouteImport } from './routes/_shell/course/$courseId/edit'
import { Route as ShellCourseCourseIdMapRouteImport } from './routes/_shell/course/$courseId/map'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdRoute = PlacePlaceIdRouteImport.update({
  id: '/place/$placeId',
  path: '/place/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendIndexRoute = RecommendIndexRouteImport.update({
  id: '/recommend/',
  path: '/recommend/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCourseIndexRoute = ShellCourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCourseCreateRoute = ShellCourseCreateRouteImport.update({
  id: '/course/create',
  path: '/course/create',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCourseDiscoverRoute = ShellCourseDiscoverRouteImport.update({
  id: '/course/discover',
  path: '/course/discover',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMapIndexRoute = ShellMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMyIndexRoute = ShellMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMyDataSourcesRoute = ShellMyDataSourcesRouteImport.update({
  id: '/my/data-sources',
  path: '/my/data-sources',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMyPermissionsRoute = ShellMyPermissionsRouteImport.update({
  id: '/my/permissions',
  path: '/my/permissions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMyPreferencesRoute = ShellMyPreferencesRouteImport.update({
  id: '/my/preferences',
  path: '/my/preferences',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMyRankingRoute = ShellMyRankingRouteImport.update({
  id: '/my/ranking',
  path: '/my/ranking',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMyReviewsRoute = ShellMyReviewsRouteImport.update({
  id: '/my/reviews',
  path: '/my/reviews',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMySavedCoursesRoute = ShellMySavedCoursesRouteImport.update({
  id: '/my/saved-courses',
  path: '/my/saved-courses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMySavedPlacesRoute = ShellMySavedPlacesRouteImport.update({
  id: '/my/saved-places',
  path: '/my/saved-places',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMyTitlesRoute = ShellMyTitlesRouteImport.update({
  id: '/my/titles',
  path: '/my/titles',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTravelersTravelerIdRoute =
  ShellTravelersTravelerIdRouteImport.update({
    id: '/travelers/$travelerId',
    path: '/travelers/$travelerId',
    getParentRoute: () => ShellRoute,
  } as any)
const LoginKakaoCallbackRoute = LoginKakaoCallbackRouteImport.update({
  id: '/login/kakao/callback',
  path: '/login/kakao/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdReviewRoute = PlacePlaceIdReviewRouteImport.update({
  id: '/place/$placeId_/review',
  path: '/place/$placeId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCourseCourseIdIndexRoute =
  ShellCourseCourseIdIndexRouteImport.update({
    id: '/course/$courseId/',
    path: '/course/$courseId/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellCourseCourseIdEditRoute = ShellCourseCourseIdEditRouteImport.update({
  id: '/course/$courseId/edit',
  path: '/course/$courseId/edit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCourseCourseIdMapRoute = ShellCourseCourseIdMapRouteImport.update({
  id: '/course/$courseId/map',
  path: '/course/$courseId/map',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/recommend/': typeof RecommendIndexRoute
  '/course/create': typeof ShellCourseCreateRoute
  '/course/discover': typeof ShellCourseDiscoverRoute
  '/my/data-sources': typeof ShellMyDataSourcesRoute
  '/my/permissions': typeof ShellMyPermissionsRoute
  '/my/preferences': typeof ShellMyPreferencesRoute
  '/my/ranking': typeof ShellMyRankingRoute
  '/my/reviews': typeof ShellMyReviewsRoute
  '/my/saved-courses': typeof ShellMySavedCoursesRoute
  '/my/saved-places': typeof ShellMySavedPlacesRoute
  '/my/titles': typeof ShellMyTitlesRoute
  '/travelers/$travelerId': typeof ShellTravelersTravelerIdRoute
  '/login/kakao/callback': typeof LoginKakaoCallbackRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
  '/course/': typeof ShellCourseIndexRoute
  '/map/': typeof ShellMapIndexRoute
  '/my/': typeof ShellMyIndexRoute
  '/course/$courseId/edit': typeof ShellCourseCourseIdEditRoute
  '/course/$courseId/map': typeof ShellCourseCourseIdMapRoute
  '/course/$courseId/': typeof ShellCourseCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/': typeof ShellIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/recommend': typeof RecommendIndexRoute
  '/course/create': typeof ShellCourseCreateRoute
  '/course/discover': typeof ShellCourseDiscoverRoute
  '/my/data-sources': typeof ShellMyDataSourcesRoute
  '/my/permissions': typeof ShellMyPermissionsRoute
  '/my/preferences': typeof ShellMyPreferencesRoute
  '/my/ranking': typeof ShellMyRankingRoute
  '/my/reviews': typeof ShellMyReviewsRoute
  '/my/saved-courses': typeof ShellMySavedCoursesRoute
  '/my/saved-places': typeof ShellMySavedPlacesRoute
  '/my/titles': typeof ShellMyTitlesRoute
  '/travelers/$travelerId': typeof ShellTravelersTravelerIdRoute
  '/login/kakao/callback': typeof LoginKakaoCallbackRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
  '/course': typeof ShellCourseIndexRoute
  '/map': typeof ShellMapIndexRoute
  '/my': typeof ShellMyIndexRoute
  '/course/$courseId/edit': typeof ShellCourseCourseIdEditRoute
  '/course/$courseId/map': typeof ShellCourseCourseIdMapRoute
  '/course/$courseId': typeof ShellCourseCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/_shell/': typeof ShellIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/recommend/': typeof RecommendIndexRoute
  '/_shell/course/create': typeof ShellCourseCreateRoute
  '/_shell/course/discover': typeof ShellCourseDiscoverRoute
  '/_shell/my/data-sources': typeof ShellMyDataSourcesRoute
  '/_shell/my/permissions': typeof ShellMyPermissionsRoute
  '/_shell/my/preferences': typeof ShellMyPreferencesRoute
  '/_shell/my/ranking': typeof ShellMyRankingRoute
  '/_shell/my/reviews': typeof ShellMyReviewsRoute
  '/_shell/my/saved-courses': typeof ShellMySavedCoursesRoute
  '/_shell/my/saved-places': typeof ShellMySavedPlacesRoute
  '/_shell/my/titles': typeof ShellMyTitlesRoute
  '/_shell/travelers/$travelerId': typeof ShellTravelersTravelerIdRoute
  '/login/kakao/callback': typeof LoginKakaoCallbackRoute
  '/place/$placeId_/review': typeof PlacePlaceIdReviewRoute
  '/_shell/course/': typeof ShellCourseIndexRoute
  '/_shell/map/': typeof ShellMapIndexRoute
  '/_shell/my/': typeof ShellMyIndexRoute
  '/_shell/course/$courseId/edit': typeof ShellCourseCourseIdEditRoute
  '/_shell/course/$courseId/map': typeof ShellCourseCourseIdMapRoute
  '/_shell/course/$courseId/': typeof ShellCourseCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/place/$placeId'
    | '/login/'
    | '/onboarding/'
    | '/recommend/'
    | '/course/create'
    | '/course/discover'
    | '/my/data-sources'
    | '/my/permissions'
    | '/my/preferences'
    | '/my/ranking'
    | '/my/reviews'
    | '/my/saved-courses'
    | '/my/saved-places'
    | '/my/titles'
    | '/travelers/$travelerId'
    | '/login/kakao/callback'
    | '/place/$placeId/review'
    | '/course/'
    | '/map/'
    | '/my/'
    | '/course/$courseId/edit'
    | '/course/$courseId/map'
    | '/course/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/place/$placeId'
    | '/'
    | '/login'
    | '/onboarding'
    | '/recommend'
    | '/course/create'
    | '/course/discover'
    | '/my/data-sources'
    | '/my/permissions'
    | '/my/preferences'
    | '/my/ranking'
    | '/my/reviews'
    | '/my/saved-courses'
    | '/my/saved-places'
    | '/my/titles'
    | '/travelers/$travelerId'
    | '/login/kakao/callback'
    | '/place/$placeId/review'
    | '/course'
    | '/map'
    | '/my'
    | '/course/$courseId/edit'
    | '/course/$courseId/map'
    | '/course/$courseId'
  id:
    | '__root__'
    | '/_shell'
    | '/place/$placeId'
    | '/_shell/'
    | '/login/'
    | '/onboarding/'
    | '/recommend/'
    | '/_shell/course/create'
    | '/_shell/course/discover'
    | '/_shell/my/data-sources'
    | '/_shell/my/permissions'
    | '/_shell/my/preferences'
    | '/_shell/my/ranking'
    | '/_shell/my/reviews'
    | '/_shell/my/saved-courses'
    | '/_shell/my/saved-places'
    | '/_shell/my/titles'
    | '/_shell/travelers/$travelerId'
    | '/login/kakao/callback'
    | '/place/$placeId_/review'
    | '/_shell/course/'
    | '/_shell/map/'
    | '/_shell/my/'
    | '/_shell/course/$courseId/edit'
    | '/_shell/course/$courseId/map'
    | '/_shell/course/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  PlacePlaceIdRoute: typeof PlacePlaceIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  RecommendIndexRoute: typeof RecommendIndexRoute
  LoginKakaoCallbackRoute: typeof LoginKakaoCallbackRoute
  PlacePlaceIdReviewRoute: typeof PlacePlaceIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId': {
      id: '/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/place/$placeId'
      preLoaderRoute: typeof PlacePlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend/': {
      id: '/recommend/'
      path: '/recommend'
      fullPath: '/recommend/'
      preLoaderRoute: typeof RecommendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/course/': {
      id: '/_shell/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof ShellCourseIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/course/create': {
      id: '/_shell/course/create'
      path: '/course/create'
      fullPath: '/course/create'
      preLoaderRoute: typeof ShellCourseCreateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/course/discover': {
      id: '/_shell/course/discover'
      path: '/course/discover'
      fullPath: '/course/discover'
      preLoaderRoute: typeof ShellCourseDiscoverRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/map/': {
      id: '/_shell/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof ShellMapIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/': {
      id: '/_shell/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof ShellMyIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/data-sources': {
      id: '/_shell/my/data-sources'
      path: '/my/data-sources'
      fullPath: '/my/data-sources'
      preLoaderRoute: typeof ShellMyDataSourcesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/permissions': {
      id: '/_shell/my/permissions'
      path: '/my/permissions'
      fullPath: '/my/permissions'
      preLoaderRoute: typeof ShellMyPermissionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/preferences': {
      id: '/_shell/my/preferences'
      path: '/my/preferences'
      fullPath: '/my/preferences'
      preLoaderRoute: typeof ShellMyPreferencesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/ranking': {
      id: '/_shell/my/ranking'
      path: '/my/ranking'
      fullPath: '/my/ranking'
      preLoaderRoute: typeof ShellMyRankingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/reviews': {
      id: '/_shell/my/reviews'
      path: '/my/reviews'
      fullPath: '/my/reviews'
      preLoaderRoute: typeof ShellMyReviewsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/saved-courses': {
      id: '/_shell/my/saved-courses'
      path: '/my/saved-courses'
      fullPath: '/my/saved-courses'
      preLoaderRoute: typeof ShellMySavedCoursesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/saved-places': {
      id: '/_shell/my/saved-places'
      path: '/my/saved-places'
      fullPath: '/my/saved-places'
      preLoaderRoute: typeof ShellMySavedPlacesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/my/titles': {
      id: '/_shell/my/titles'
      path: '/my/titles'
      fullPath: '/my/titles'
      preLoaderRoute: typeof ShellMyTitlesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/travelers/$travelerId': {
      id: '/_shell/travelers/$travelerId'
      path: '/travelers/$travelerId'
      fullPath: '/travelers/$travelerId'
      preLoaderRoute: typeof ShellTravelersTravelerIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/login/kakao/callback': {
      id: '/login/kakao/callback'
      path: '/login/kakao/callback'
      fullPath: '/login/kakao/callback'
      preLoaderRoute: typeof LoginKakaoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId_/review': {
      id: '/place/$placeId_/review'
      path: '/place/$placeId/review'
      fullPath: '/place/$placeId/review'
      preLoaderRoute: typeof PlacePlaceIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/course/$courseId/': {
      id: '/_shell/course/$courseId/'
      path: '/course/$courseId'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof ShellCourseCourseIdIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/course/$courseId/edit': {
      id: '/_shell/course/$courseId/edit'
      path: '/course/$courseId/edit'
      fullPath: '/course/$courseId/edit'
      preLoaderRoute: typeof ShellCourseCourseIdEditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/course/$courseId/map': {
      id: '/_shell/course/$courseId/map'
      path: '/course/$courseId/map'
      fullPath: '/course/$courseId/map'
      preLoaderRoute: typeof ShellCourseCourseIdMapRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellCourseCreateRoute: typeof ShellCourseCreateRoute
  ShellCourseDiscoverRoute: typeof ShellCourseDiscoverRoute
  ShellMyDataSourcesRoute: typeof ShellMyDataSourcesRoute
  ShellMyPermissionsRoute: typeof ShellMyPermissionsRoute
  ShellMyPreferencesRoute: typeof ShellMyPreferencesRoute
  ShellMyRankingRoute: typeof ShellMyRankingRoute
  ShellMyReviewsRoute: typeof ShellMyReviewsRoute
  ShellMySavedCoursesRoute: typeof ShellMySavedCoursesRoute
  ShellMySavedPlacesRoute: typeof ShellMySavedPlacesRoute
  ShellMyTitlesRoute: typeof ShellMyTitlesRoute
  ShellTravelersTravelerIdRoute: typeof ShellTravelersTravelerIdRoute
  ShellCourseIndexRoute: typeof ShellCourseIndexRoute
  ShellMapIndexRoute: typeof ShellMapIndexRoute
  ShellMyIndexRoute: typeof ShellMyIndexRoute
  ShellCourseCourseIdEditRoute: typeof ShellCourseCourseIdEditRoute
  ShellCourseCourseIdMapRoute: typeof ShellCourseCourseIdMapRoute
  ShellCourseCourseIdIndexRoute: typeof ShellCourseCourseIdIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellCourseCreateRoute: ShellCourseCreateRoute,
  ShellCourseDiscoverRoute: ShellCourseDiscoverRoute,
  ShellMyDataSourcesRoute: ShellMyDataSourcesRoute,
  ShellMyPermissionsRoute: ShellMyPermissionsRoute,
  ShellMyPreferencesRoute: ShellMyPreferencesRoute,
  ShellMyRankingRoute: ShellMyRankingRoute,
  ShellMyReviewsRoute: ShellMyReviewsRoute,
  ShellMySavedCoursesRoute: ShellMySavedCoursesRoute,
  ShellMySavedPlacesRoute: ShellMySavedPlacesRoute,
  ShellMyTitlesRoute: ShellMyTitlesRoute,
  ShellTravelersTravelerIdRoute: ShellTravelersTravelerIdRoute,
  ShellCourseIndexRoute: ShellCourseIndexRoute,
  ShellMapIndexRoute: ShellMapIndexRoute,
  ShellMyIndexRoute: ShellMyIndexRoute,
  ShellCourseCourseIdEditRoute: ShellCourseCourseIdEditRoute,
  ShellCourseCourseIdMapRoute: ShellCourseCourseIdMapRoute,
  ShellCourseCourseIdIndexRoute: ShellCourseCourseIdIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  PlacePlaceIdRoute: PlacePlaceIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  RecommendIndexRoute: RecommendIndexRoute,
  LoginKakaoCallbackRoute: LoginKakaoCallbackRoute,
  PlacePlaceIdReviewRoute: PlacePlaceIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
